name: Tests

on:
  - push
  - pull_request

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Get Jira Issue Tests
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Run Action
      uses: ./
      id: run-action-1
      with:
        search-string: 'ABC-123'

    - name: Failed
      if: ${{ steps.run-action-1.outputs.issue-key != 'ABC-123'}}
      run: |
        exit 1

    - name: Verify .jira.d config file is written
      run: cat $HOME/.jira.d/config.yml

    - name: Verify jira config file is written
      run: cat $HOME/jira/config.yml

    - name: Run Action
      uses: ./
      id: run-action-2
      with:
        search-string: 'ABC-123 And a bunch of other stuff'

    - name: Failed
      if: ${{ steps.run-action-2.outputs.issue-key != 'ABC-123'}}
      run: |
        exit 1

    - name: Run Action
      uses: ./
      id: run-action-3
      with:
        search-string: 'In the middle again ABC-123 And a bunch of other stuff'

    - name: Failed
      if: ${{ steps.run-action-3.outputs.issue-key != 'ABC-123'}}
      run: |
        exit 1

    - name: Run Action
      uses: ./
      id: run-action-4
      with:
        search-string: 'At the end is ABC-123'

    - name: Failed
      if: ${{ steps.run-action-4.outputs.issue-key != 'ABC-123'}}
      run: |
        exit 1

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12

    - name: Install dependencies
      run: npm ci
